[package]
name = "cred-man"
version = "1.1.0"
authors = ["Dmitry Kalyanov <Kalyanov.Dmitry@gmail.com>"]
edition = "2018"

[lib]
name = "cred_man_lib"

[dependencies]
linenoise-rust = "0.2.1"
rustc-serialize = "0.3.24"
rust-crypto = "0.2.36"
getrandom = "0.1.13"
chrono = "0.4.10"
gtk = { version = "0.7.0", features = ["embed-lgpl-docs", "v3_16"] }
glib = "0.8.2"
dirs = "2.0.2"
