[package]
name = "cred-man"
version = "0.1.0"
authors = ["Dmitry Kalyanov <Kalyanov.Dmitry@gmail.com>"]

[dependencies]
linenoise-rust = "0.1.12"
rustc-serialize = "0.3"
rust-crypto = "*"
rand = "*"
chrono = "0.2"