[package]
name = "cred-man"
version = "1.1.0"
authors = ["Dmitry Kalyanov <Kalyanov.Dmitry@gmail.com>"]
edition = "2021"

[lib]
name = "cred_man_lib"

[dependencies]
linenoise-rust = "0.2.1"
rust-crypto = "0.2.36"
getrandom = "0.2.9"
chrono = "0.4.10"
gtk = { version = "0.17.1", features = ["v3_24"] }
glib = "0.17.9"
dirs = "5.0.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
