[package]
name = "cred-man"
version = "1.0.1"
authors = ["Dmitry Kalyanov <Kalyanov.Dmitry@gmail.com>"]

[lib]
name = "cred_man_lib"

[dependencies]
linenoise-rust = "0.1.12"
rustc-serialize = "0.3"
rust-crypto = "0.2.34"
rand = "0.3.11"
chrono = "0.2"