[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cred_man_gtk"
path = "src/main.rs"

[dependencies]
cred-man = { workspace = true }
glib = "0.18.3"
gtk = { version = "0.18.1", features = ["v3_24"] }